config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'

  resources :restaurants, only: [:index, :new, :create]

  resources :restaurants, only: [:show] do
    resources :reviews, only: [:new, :create]
  end

  resources :categories, only: [:index, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurantcuisines
  has_many :restaurants, through: :restaurantcuisines
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  has_many :restaurantcuisines
  has_many :categories, through: :restaurantcuisines

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, length: { is: 5 }, numericality: true

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end

  def show_categories
    array = []
    categories.each do |category|
      array << category.name
    end
    array.join(', ')
  end
end

app/models/restaurantcuisine.rb
class Restaurantcuisine < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :category
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :body, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: (1..5), message: "Must be between 1 - 5"}
  def parse_create_date
    "#{created_at.strftime("%B %d %Y")}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
    @category_collection = Category.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant added successfully'
    else
      @category_collection = Category.all
      render :new
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zip, :description, category_ids: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'Review added successfully'
    else
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
Categories:

<ul>
<% @categories.each do |category| %>
  <li>
  <%= link_to category.name, category_path(category) %>
</li>
<% end %>
</ul>

app/views/categories/show.html.erb
<%= @category.name %>

<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant_path(restaurant) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
    <div class="flash flash-<%= type %>">
      <%= message %>
    </div>
  <% end %>

  <%= link_to "Categories", categories_path %>

  <%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>

  <% if @restaurant.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <%= @restaurant.errors.full_messages.join('. ') %>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <%= f.label :description %>
  <%= f.text_field :description %>

<% unless @category_collection.nil? %>
  <div>
    <%= f.label :categories %>
    <%= f.collection_check_boxes(:category_ids, @category_collection, :id, :name) %>
  </div>
<% end %>

  <div class="actions">
    <%= f.submit 'Add Restaurant', class: 'button tiny'%>
  </div>

<% end %>

app/views/restaurants/index.html.erb
Restaurant Index Page

<%= link_to 'Add New Restaurant', new_restaurant_path %>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
New Restaurant Form

<%= render 'form' %>

app/views/restaurants/show.html.erb
Restaurant Show Page
<br>
Name: <%= @restaurant.name %>
<br>
Address: <%= @restaurant.full_address %>
Description: <%= @restaurant.description %>
Categories: <%= @restaurant.show_categories %>

<%= link_to 'Add a Review', new_restaurant_review_path(@restaurant) %>

<% if @reviews.any? %>
Reviews:
<ul>
<% @reviews.each do |review| %>
<li>
  Rating: <%= review.rating %>
  Body: <%= review.body %>
  Posted On: <%= review.parse_create_date %>
</li>
<% end %>
</ul>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for [@restaurant, @review] do |f| %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <%= @review.errors.full_messages.join('. ') %>
      <ul>
    </div>
  <% end %>

    <%= f.label :rating %>
    <%= f.text_field :rating %>
    <%= f.label :body, 'Review' %>
    <%= f.text_field :body %>

  <div class="actions">
    <%= f.submit 'Add Review', class: 'button tiny'%>
  </div>

<% end %>

app/views/reviews/new.html.erb
Review Form for <%= @restaurant.name %>

<%= render 'form' %>